2019-03-13 23:44:22,007 ERROR: Exception on /reset_password_request [POST] [in /Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/shaquillewyanque/git/microblog/app/routes.py", line 141, in reset_password_request
    send_password_reset_email(user)
  File "/Users/shaquillewyanque/git/microblog/app/email.py", line 14, in send_password_reset_email
    sender=app.config['ADMIN'][0],
IndexError: list index out of range
2019-03-13 23:46:06,314 INFO: Microblog startup [in /Users/shaquillewyanque/git/microblog/app/__init__.py:45]
2019-03-13 23:46:09,362 ERROR: Exception on /reset_password_request [POST] [in /Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/shaquillewyanque/git/microblog/app/routes.py", line 141, in reset_password_request
    send_password_reset_email(user)
  File "/Users/shaquillewyanque/git/microblog/app/email.py", line 14, in send_password_reset_email
    sender=app.config['ADMIN'][0],
IndexError: list index out of range
2019-03-13 23:46:35,136 INFO: Microblog startup [in /Users/shaquillewyanque/git/microblog/app/__init__.py:45]
2019-03-13 23:46:39,345 ERROR: Exception on /reset_password_request [POST] [in /Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/shaquillewyanque/git/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/shaquillewyanque/git/microblog/app/routes.py", line 141, in reset_password_request
    send_password_reset_email(user)
  File "/Users/shaquillewyanque/git/microblog/app/email.py", line 14, in send_password_reset_email
    sender=app.config['ADMIN'][0],
IndexError: list index out of range
2019-03-13 23:51:38,304 INFO: Microblog startup [in /Users/shaquillewyanque/git/microblog/app/__init__.py:45]
2019-03-13 23:56:41,501 INFO: Microblog startup [in /Users/shaquillewyanque/git/microblog/app/__init__.py:45]
2019-03-13 23:57:13,837 INFO: Microblog startup [in /Users/shaquillewyanque/git/microblog/app/__init__.py:45]
